sudo: required
language: generic
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

deploy:
  provider: script
  script:
    - make build
    # Take those images and push themto docker hub
    - make push
  on:
    branch: master
